# Generated by Django 4.1.6 on 2023-02-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleague_ordering', '0002_alter_position_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
